config/routes.rb
Rails.application.routes.draw do

  resources :products
  get 'users/new'

  root to: 'static_pages#home'

  #get 'static_pages/home'
  get '/home', to: 'static_pages#home'
  get '/', to: 'static_pages#home'


  #get 'static_pages/help'
  get '/help', to: 'static_pages#help'

  #get 'static_pages/about'
  get '/about', to: 'static_pages#about'

  get '/contact', to:'static_pages#contact'
  get 'static_pages/nothing'

  get '/signup', to:'users#new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  price      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
#  attr_accessor :name, :email, :password, :password_confirmation
  has_secure_password
  before_save { |user| user.email = email.downcase}

  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, length: {maximum: 50} , format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  attr_accessor :val
  @@val = 0
  def home
      @@val=@@val+1

      @ins=@@val
      puts @ins
  end

  def help
  end

  def about
  end

  def nothing
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title)
    base_title ="Ruby on Rails Tutorial Sample App "
    if(title.empty?)
      base_title
    else
      "#{base_title} | #{title}"
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://railstutorial.org/">Rails Tutorial</a>
by <%= link_to "Surya DaVinci", "https://github.com/suryadavinci" %>
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("rails-logo.svg", alt: "Rails", width: "30", height: "30"), 'http://rubyonrails.org/' %>
<%= link_to "sample app", "#", id: "logo" %>
       <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",root_path %></li>
          <li> <%= link_to "Help", help_path %></li>
          <li> <%= link_to "Sign In","#" %></li>
        </ul>
      </nav>
      <!-- <nav>
      <ul class="nav pull-right">
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      </ul>
      </nav> -->
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>


    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>


      <%= debug (params) if Rails.env.development? %>
      <br/>
      <%= params.inspect %>
    </div>

  </body>
</html>
<!--application.html.erb-->

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<%provide(:title, 'About Us')%>
<h1>About Us</h1>
<p>
The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
  <h1>Contact Us</h1>
  <h2><%= link_to "Surya DaVinci","https://github.com/suryadavinci" %></h2>
  <h3>Residence</h3>
  <h4>Pondicherry</h4>
  <h5>Office</h5>
  <h6>Chennai</h6>

  <p>Find me in app/views/static_pages/nothing.html.erb</p>

app/views/static_pages/help.html.erb
<%provide(:title, 'Help')%>
  <h1>StaticPages#help</h1>
  <p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<%provide(:title, 'Home')%>
<div class="center hero-unit">
  <h1>Welcome to Sample App</h1>
  <h2>This is the sample app for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails-logo.svg", alt: "Rails", width: "220", height: "78"), 'http://rubyonrails.org/' %>
<br/>
<p>
Page visit count <%= @ins %>
</p>

app/views/static_pages/nothing.html.erb
  <h1>StaticPages#Nothing</h1>
  <p>Find me in app/views/static_pages/nothing.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, "Sign Up" ) %>

<h1>Sign Up</h1>
<p>Find me in app/views/users/new.html.erb</p>